AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating EventBridge rule to forward EKS health events to another EventBridge bus'

Parameters:
  TargetEventBusArn:
    Type: String
    Description: 'ARN of the target event bus (e.g., arn:aws:events:us-west-2:123456789012:event-bus/central-bus)'

Resources:
  # IAM Role for cross-account EventBridge access
  EventBridgeCrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      # Trust policy allowing EventBridge to assume this role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      # Inline policy granting permission to put events on the target bus
      Policies:
        - PolicyName: EventBridgeCrossAccountPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'events:PutEvents'
                Resource: !Ref TargetEventBusArn

  # EventBridge rule to capture and forward EKS health events
  EKSHealthEventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: 'EKSHealthEventsRule'
      Description: 'Capture EKS health events and forward to central event bus'
      # Event pattern to filter for specific EKS health events
      EventPattern:
        source:
          - 'aws.health'
        detail-type:
          - 'AWS Health Event'
        detail:
          service:
            - 'EKS'
          eventTypeCategory:
            - 'scheduledChange'
          eventTypeCode:
            - 'AWS_EKS_PLANNED_LIFECYCLE_EVENT'
      State: 'ENABLED'
      # Target configuration for forwarding events
      Targets:
        - Arn: !Ref TargetEventBusArn
          Id: 'CentralEventBus'
          RoleArn: !GetAtt EventBridgeCrossAccountRole.Arn

Outputs:
  # Output the ARN of the created EventBridge rule
  EventBridgeRuleArn:
    Description: 'ARN of the created EventBridge rule'
    Value: !GetAtt EKSHealthEventsRule.Arn
  # Output the ARN of the IAM role for cross-account event routing
  CrossAccountRoleArn:
    Description: 'ARN of the IAM role for cross-account event routing'
    Value: !GetAtt EventBridgeCrossAccountRole.Arn